### ISSUE TITLE
关于成绩查询的接口问题

### ISSUE THREAD

**Issue by zangjiahe** [jokerwho/zfnew_webApi#8]
之前查询成绩的接口有个可以直接返回所有学期成绩的接口，但是好像失效了，请问您的改接口有是否还有效呢？
域名/cjcx/cjcx_cxDgXscj.html?doType=query&gnmkdm=N305005

**Comment by zaigie** [comment]
我刚刚看了一下，提示无功能权限，应该是公司关闭了这个接口或者学校选择性关闭了

**Comment by zangjiahe** [comment]
应该是公司关闭了该接口  得自己获取每个学期的成绩然后拼接出来了~
